# Generated by Django 2.1.8 on 2021-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketer001_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('amount', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='marketer002_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='marketer003_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer004_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer005_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer006_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer007_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer008_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer009_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer010_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer011_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer012_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer013_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer014_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer015_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer016_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer017_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer018_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer019_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketer020_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_username', models.CharField(max_length=40)),
                ('other_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
