# Generated by Django 2.1.8 on 2021-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gent_marketering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEM001_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('amount', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GEM002_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GEM003_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM004_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM005_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM006_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM007_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM008_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM009_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM010_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM011_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM012_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM013_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM014_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM015_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM016_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM017_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM018_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM019_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GEM020_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=40)),
                ('client_names', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='marketer001_client',
        ),
        migrations.DeleteModel(
            name='marketer002_client',
        ),
        migrations.DeleteModel(
            name='marketer003_client',
        ),
        migrations.DeleteModel(
            name='marketer004_client',
        ),
        migrations.DeleteModel(
            name='marketer005_client',
        ),
        migrations.DeleteModel(
            name='marketer006_client',
        ),
        migrations.DeleteModel(
            name='marketer007_client',
        ),
        migrations.DeleteModel(
            name='marketer008_client',
        ),
        migrations.DeleteModel(
            name='marketer009_client',
        ),
        migrations.DeleteModel(
            name='marketer010_client',
        ),
        migrations.DeleteModel(
            name='marketer011_client',
        ),
        migrations.DeleteModel(
            name='marketer012_client',
        ),
        migrations.DeleteModel(
            name='marketer013_client',
        ),
        migrations.DeleteModel(
            name='marketer014_client',
        ),
        migrations.DeleteModel(
            name='marketer015_client',
        ),
        migrations.DeleteModel(
            name='marketer016_client',
        ),
        migrations.DeleteModel(
            name='marketer017_client',
        ),
        migrations.DeleteModel(
            name='marketer018_client',
        ),
        migrations.DeleteModel(
            name='marketer019_client',
        ),
        migrations.DeleteModel(
            name='marketer020_client',
        ),
    ]
