# Generated by Django 2.1.8 on 2021-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_referal',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
