# Generated by Django 2.1.8 on 2021-03-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0005_referral_account_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral_account',
            name='user',
        ),
        migrations.AddField(
            model_name='user_referal',
            name='Referal_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_referal',
            name='numbers_refered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_referal',
            name='request',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='referral_account',
        ),
    ]
