# Generated by Django 2.1.8 on 2021-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0006_auto_20210330_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_referal',
            name='Referal_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_referal',
            name='numbers_refered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
