# Generated by Django 2.1.8 on 2021-04-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0007_auto_20210331_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_referal',
            old_name='request',
            new_name='request_bonus',
        ),
    ]
