# Generated by Django 2.1.8 on 2021-04-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0008_auto_20210401_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_referal',
            name='payment_status',
            field=models.CharField(choices=[('None', 'NONE'), ('payment_pending', 'payment_pending'), ('payment_rejected', 'payment_rejected')], default='None', max_length=20),
        ),
    ]
