# Generated by Django 2.1.8 on 2021-04-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0009_user_referal_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_referal',
            name='payment_status',
            field=models.CharField(choices=[('None', 'NONE'), ('payment_pending', 'payment_pending'), ('Payment_made', 'Payment_made'), ('payment_rejected', 'payment_rejected')], default='None', max_length=20),
        ),
    ]
