# Generated by Django 2.1.8 on 2021-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0010_auto_20210402_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_referal',
            name='minus_Referal_bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_referal',
            name='minus_numbers_refered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
