# Generated by Django 2.1.8 on 2021-04-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0011_auto_20210403_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_referal',
            name='minus_Referal_bonus',
        ),
        migrations.RemoveField(
            model_name='user_referal',
            name='minus_numbers_refered',
        ),
    ]
