# Generated by Django 2.1.8 on 2021-04-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0012_auto_20210403_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_referal',
            name='withdrawed_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
