# Generated by Django 2.1.8 on 2021-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieReferal', '0013_user_referal_withdrawed_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_referal',
            old_name='withdrawed_bonus',
            new_name='requested_bonus',
        ),
        migrations.AddField(
            model_name='user_referal',
            name='total_withdrawed_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
