# Generated by Django 2.1.8 on 2021-06-20 19:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify_all_user',
            name='message',
            field=tinymce.models.HTMLField(blank='True', max_length=999, null='true'),
        ),
    ]
