# Generated by Django 2.1.8 on 2021-07-15 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gentannieApp', '0002_auto_20210620_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSmart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, default='super', max_length=30, null=True)),
                ('plan_name', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium'), ('bronze', 'bronze'), ('super_bronze', 'super_bronze'), ('silver', 'silver'), ('super_silver', 'super_silver'), ('Gold', 'Gold'), ('diamond', 'diamond'), ('Ruby', 'Ruby'), ('peal', 'peal'), ('emerald', 'emerald'), ('Jasper', 'Jasper')], max_length=30)),
                ('amount_deposited', models.CharField(default=0.0, max_length=20)),
                ('ROI', models.CharField(default=0.0, max_length=20)),
                ('deposit_status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], default='pending', max_length=15)),
                ('payment_status', models.CharField(blank=True, choices=[('payment_pending', 'payment_pending'), ('payment_done', 'payment_done'), ('payment_declined', 'payment_declined')], default=None, max_length=20, null=True)),
                ('account_type', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=30)),
                ('request', models.BooleanField(default=False)),
                ('payment_proof', models.FileField(upload_to='images')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_count', models.IntegerField(default=0)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='super',
            name='username',
        ),
        migrations.AlterField(
            model_name='notify_all_user',
            name='message',
            field=tinymce.models.HTMLField(default='', max_length=999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='super',
        ),
    ]
