# Generated by Django 2.1.8 on 2021-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieApp', '0003_auto_20210715_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersmart',
            name='plan',
            field=models.CharField(blank=True, default='SuperSmart', max_length=30, null=True),
        ),
    ]
