# Generated by Django 2.1.8 on 2022-04-30 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gentannieApp', '0004_auto_20210717_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
